// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"database/sql"
)

type Addresses struct {
	AddressID int64
	Latitude  float64
	Longitude float64
}

type Locations struct {
	LocationID   int64
	LocationName string
	AddressID    int64
}

type Products struct {
	ProductID   int64
	ProductName string
	Description sql.NullString
	UnitPrice   float64
	SupplierID  int64
}

type Stocks struct {
	ProductID  sql.NullInt64
	LocationID sql.NullInt64
	Quantity   int64
}

type Suppliers struct {
	SupplierID   int64
	SupplierName string
	Phone        string
	Mail         string
}
