// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"database/sql"
)

type Address struct {
	AddressID int32
	Latitude  float64
	Longitude float64
}

type Location struct {
	LocationID   int32
	LocationName string
	AddressID    int32
}

type Product struct {
	ProductID   int32
	ProductName string
	Description sql.NullString
	UnitPrice   float64
	SupplierID  int32
}

type Stock struct {
	ProductID  int32
	LocationID int32
	Quantity   int32
}

type Supplier struct {
	SupplierID   int32
	SupplierName string
	Phone        string
	Mail         string
}
